from django.db import models

# Create your models here.
from django.db import models
import uuid

# Create your models here.

class arcinfo(models.Model):
    company = models.CharField(max_length=200, null=True, blank=True)
    owner = models.CharField(max_length=200, null=True, blank=True)
    contact = models.CharField(max_length=200, null=True, blank=True)
    manager = models.CharField(max_length=200, null=True, blank=True)
    managercont = models.CharField(max_length=200, null=True, blank=True)
    estimate = models.CharField(max_length=200, null=True, blank=True)
    wi1 = models.ImageField(upload_to='images/',null=True, blank=True)
    wi2 = models.ImageField(upload_to='images/',null=True, blank=True)
    wi3 = models.ImageField(upload_to='images/',null=True, blank=True)
    wi4 = models.ImageField(upload_to='images/',null=True, blank=True)
    wi5 = models.ImageField(upload_to='images/',null=True, blank=True)
    wi6 = models.ImageField(upload_to='images/',null=True, blank=True)

class arcloc(models.Model):
    address = models.CharField(max_length=200, null=True, blank=True)

class financial(models.Model):
    labor = models.CharField(max_length=200, null=True, blank=True)
    part = models.CharField(max_length=200, null=True, blank=True)
    material = models.CharField(max_length=200, null=True, blank=True)
    rent = models.CharField(max_length=200, null=True, blank=True)
    productive = models.CharField(max_length=200, null=True, blank=True)
    support = models.CharField(max_length=200, null=True, blank=True)
    month = models.CharField(max_length=200, null=True, blank=True)

class workforceinfo(models.Model):
    PPE = models.CharField(max_length=200, null=True, blank=True)
    denter = models.CharField(max_length=200, null=True, blank=True)
    painter = models.CharField(max_length=200, null=True, blank=True)
    elec = models.CharField(max_length=200, null=True, blank=True)
    staff = models.CharField(max_length=200, null=True, blank=True)
    workbays = models.CharField(max_length=200, null=True, blank=True)
    body = models.CharField(max_length=200, null=True, blank=True)
    nonbody = models.CharField(max_length=200, null=True, blank=True)
    sqm = models.CharField(max_length=200, null=True, blank=True)
    insurance = models.CharField(max_length=200, null=True, blank=True)
    walkin = models.CharField(max_length=200, null=True, blank=True)
    fleet = models.CharField(max_length=200, null=True, blank=True)
    park = models.CharField(max_length=200, null=True, blank=True)
    recep = models.CharField(max_length=200, null=True, blank=True)
    wash = models.CharField(max_length=200, null=True, blank=True)
    washstaff = models.CharField(max_length=200, null=True, blank=True)
    scrap = models.CharField(max_length=200, null=True, blank=True)
    newpart = models.CharField(max_length=200, null=True, blank=True)
    oilstorage = models.CharField(max_length=200, null=True, blank=True)

class repairinfo(models.Model):
    measure = models.CharField(max_length=200, null=True, blank=True)
    nonstruct = models.CharField(max_length=200, null=True, blank=True)
    struct = models.CharField(max_length=200, null=True, blank=True)
    paint = models.CharField(max_length=200, null=True, blank=True)
    ac = models.CharField(max_length=200, null=True, blank=True)
    body = models.CharField(max_length=200, null=True, blank=True)
    qc = models.CharField(max_length=200, null=True, blank=True)
    brakes = models.CharField(max_length=200, null=True, blank=True)
    tyre = models.CharField(max_length=200, null=True, blank=True)
    wheel = models.CharField(max_length=200, null=True, blank=True)
    computer = models.CharField(max_length=200, null=True, blank=True)
    adas = models.CharField(max_length=200, null=True, blank=True)
    engine = models.CharField(max_length=200, null=True, blank=True)
    plastic = models.CharField(max_length=200, null=True, blank=True)
    welder = models.CharField(max_length=200, null=True, blank=True)

class equipinfo(models.Model):
    it = models.CharField(max_length=200, null=True, blank=True)
    comp = models.CharField(max_length=200, null=True, blank=True)
    access = models.CharField(max_length=200, null=True, blank=True)
    oem = models.CharField(max_length=200, null=True, blank=True)
    guide = models.CharField(max_length=200, null=True, blank=True)
    lift = models.CharField(max_length=200, null=True, blank=True)
    frame = models.CharField(max_length=200, null=True, blank=True)
    four = models.CharField(max_length=200, null=True, blank=True)
    anchor = models.CharField(max_length=200, null=True, blank=True)
    ton = models.CharField(max_length=200, null=True, blank=True)
    oxy = models.CharField(max_length=200, null=True, blank=True)
    resistance = models.CharField(max_length=200, null=True, blank=True)
    heater = models.CharField(max_length=200, null=True, blank=True)
    plasma = models.CharField(max_length=200, null=True, blank=True)
    mig = models.CharField(max_length=200, null=True, blank=True)
    dent = models.CharField(max_length=200, null=True, blank=True)
    air = models.CharField(max_length=200, null=True, blank=True)
    chain = models.CharField(max_length=200, null=True, blank=True)
    charging = models.CharField(max_length=200, null=True, blank=True)
    kit = models.CharField(max_length=200, null=True, blank=True)
    dry = models.CharField(max_length=200, null=True, blank=True)
    hvlp = models.CharField(max_length=200, null=True, blank=True)
    vet = models.CharField(max_length=200, null=True, blank=True)
    booth = models.CharField(max_length=200, null=True, blank=True)
    prep = models.CharField(max_length=200, null=True, blank=True)
    mixing = models.CharField(max_length=200, null=True, blank=True)
    tools = models.CharField(max_length=200, null=True, blank=True)
    toolkit = models.CharField(max_length=200, null=True, blank=True)
    lifts = models.CharField(max_length=200, null=True, blank=True)
    align = models.CharField(max_length=200, null=True, blank=True)
    rise = models.CharField(max_length=200, null=True, blank=True)
    changer = models.CharField(max_length=200, null=True, blank=True)
    balancer = models.CharField(max_length=200, null=True, blank=True)
    lathe = models.CharField(max_length=200, null=True, blank=True)
    notes = models.CharField(max_length=200, null=True, blank=True)
